### ISSUE TITLE
Шаблоны в подпапках

### ISSUE THREAD

**Issue by sazanof** [Ser1ous/seriousCustomTemplate#1]
Здравствуйте! Вопрос следующий. 
Я решил шаблоны перенести в подпапки: views/pages/login.blade.php
Заметил, что BaseController отрабатывает, а вот `class LkController extends BaseController` перестает. В этом контроллере, как описано в мануалах, я создаю методы, в которых назначаю переменные this->data, если шаблон в корне, то все работает корректно, если в подпапке - то нет
```
<?php
namespace EvolutionCMS\Adm\Controllers;
class LkController extends BaseController
{
    protected $menu = array();
    public function render()
    {
        $this->data['test'] = 'test data';
    }

    public function noCacheRender()
    {
        $data['menu'] = $this->menuOpts();
        $data['res'] = $this->evo->runSnippet('lk');
    }

    private function menuOpts(){
        $this->data['menu'] = array(
            'key' => 'act',
            'items' => array(
                'index' => 'one',
                'profile' => 'two',
                'avto' => 'tree',
                'orders' => 'four'
            )
        );
        return;
    }
}
```
может собственно дело в ерунде, не могу точно определить.)) Подскажете?

**Comment by Ser1ous** [comment]
У меня тоже есть вложенные в папках. Чтобы composer увидел эти файлы во вложенной папке, необходимо прописать namespace c учётом этой папки. Вот в качестве примера как это работает
https://monosnap.com/file/DlYiAKdbIjXEr2EMNjwgR63awrxfHW

**Comment by sazanof** [comment]
Спасибо. Я собственно так и делал, но не создал папку. Подумал, что это должно работать как-то исходя из названия псевдонима шаблона, лежащего в views/pages и алиаса шаблона pages.lk
Спасибо за разъяснения.
